// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/application/users/queries/get-user/get-user-by-id.go

// Package mock_getuserbyid is a generated GoMock package.
package mock_getuserbyid

import (
	_ "clean-architecture/pkg/application/common/exception"
)
